server:
  #端口号
  port: 80
  #项目名，如果不设定，默认是 /
  context-path: /

spring:
  datasource:
    url: jdbc:mysql://hk.wxyun.site:9928/yunpan?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: wanxing
    password: CHINA.wxyun.site

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
